CREATE TABLE `chattels` (
	`id` int AUTO_INCREMENT NOT NULL,
	`property_id` int NOT NULL,
	`name` varchar(256) NOT NULL,
	`category` enum('kitchen','heating_cooling','ventilation','floor_coverings','window_treatments','hot_water','outdoor','other') NOT NULL,
	`make_model` varchar(256),
	`serial_number` varchar(128),
	`install_date` varchar(32),
	`estimated_age` varchar(64),
	`estimated_value` varchar(64),
	`condition_at_registration` enum('new','excellent','good','fair','poor') DEFAULT 'good',
	`current_condition` enum('new','excellent','good','fair','poor') DEFAULT 'good',
	`photo_url` text,
	`photo_key` varchar(512),
	`notes` text,
	`is_healthy_homes_item` boolean DEFAULT false,
	`healthy_homes_category` enum('heating','ventilation','insulation','moisture','draught'),
	`last_checked_at` timestamp,
	`last_checked_inspection_id` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `chattels_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `healthy_homes_assessments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`property_id` int NOT NULL,
	`inspection_id` int,
	`inspector_id` int NOT NULL,
	`climate_zone` enum('1','2','3') NOT NULL,
	`heating_compliant` boolean,
	`heating_device_type` varchar(128),
	`heating_capacity_kw` varchar(32),
	`heating_required_kw` varchar(32),
	`heating_notes` text,
	`heating_photo_url` text,
	`insulation_compliant` boolean,
	`ceiling_insulation_r_value` varchar(32),
	`underfloor_insulation_r_value` varchar(32),
	`ceiling_insulation_notes` text,
	`underfloor_insulation_notes` text,
	`insulation_photo_url` text,
	`ventilation_compliant` boolean,
	`kitchen_extractor_fan` boolean,
	`bathroom_extractor_fan` boolean,
	`openable_windows_compliant` boolean,
	`ventilation_notes` text,
	`moisture_compliant` boolean,
	`gutter_condition` enum('good','fair','poor','na') DEFAULT 'na',
	`subfloor_moisture_barrier` boolean,
	`moisture_notes` text,
	`draught_compliant` boolean,
	`unused_fireplaces_blocked` boolean,
	`draught_notes` text,
	`overall_compliant` boolean,
	`compliance_date` timestamp,
	`ai_summary` text,
	`status` enum('draft','completed','report_sent') DEFAULT 'draft',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `healthy_homes_assessments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `inventory_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`inspection_id` int NOT NULL,
	`property_id` int NOT NULL,
	`name` varchar(256) NOT NULL,
	`category` enum('whiteware','furniture','appliances','tools_equipment','soft_furnishings','electronics','other') NOT NULL,
	`quantity` int DEFAULT 1,
	`condition` enum('new','excellent','good','fair','poor','damaged','missing') DEFAULT 'good',
	`description` text,
	`serial_number` varchar(128),
	`photo_url` text,
	`photo_key` varchar(512),
	`notes` text,
	`is_ai_generated` boolean DEFAULT false,
	`move_in_condition` enum('new','excellent','good','fair','poor','damaged','missing'),
	`move_out_condition` enum('new','excellent','good','fair','poor','damaged','missing'),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `inventory_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `maintenance_plan_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`property_id` int NOT NULL,
	`title` varchar(256) NOT NULL,
	`description` text,
	`location` varchar(256),
	`traffic_light` enum('green','orange','red') NOT NULL,
	`estimated_cost_bracket` enum('under_500','500_2000','2000_10000','over_10000'),
	`recommended_action` text,
	`urgency_timeline` varchar(128),
	`due_by_month` int,
	`source_inspection_id` int,
	`chattel_id` int,
	`is_ai_generated` boolean DEFAULT true,
	`status` enum('open','in_progress','completed','deferred') DEFAULT 'open',
	`completed_at` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `maintenance_plan_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `pm_review_queue` (
	`id` int AUTO_INCREMENT NOT NULL,
	`inspection_id` int NOT NULL,
	`property_id` int NOT NULL,
	`assigned_to_user_id` int,
	`status` enum('pending','in_review','approved','rejected','sent') DEFAULT 'pending',
	`tenant_letter_draft` text,
	`tenant_letter_approved` boolean DEFAULT false,
	`maintenance_requests_created` boolean DEFAULT false,
	`maintenance_request_count` int DEFAULT 0,
	`pdf_report_ready` boolean DEFAULT false,
	`pdf_report_url` text,
	`reviewed_at` timestamp,
	`sent_at` timestamp,
	`agent_notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `pm_review_queue_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `rental_appraisals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`property_id` int NOT NULL,
	`inspection_id` int,
	`current_rent` varchar(32),
	`recommended_rent_low` varchar(32),
	`recommended_rent_high` varchar(32),
	`market_median` varchar(32),
	`condition_premium_discount` varchar(32),
	`comparable_analysis` text,
	`market_sentiment` enum('rising','stable','softening') DEFAULT 'stable',
	`vacancy_rate` varchar(32),
	`ai_draft_report` text,
	`pdf_url` text,
	`status` enum('draft','finalised','sent') DEFAULT 'draft',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `rental_appraisals_id` PRIMARY KEY(`id`)
);
