/**
 * FXD Inspector — Disclaimer Constants
 * ─────────────────────────────────
 * All user-facing disclaimers are defined here in one place.
 * Legal review should be conducted against this file only.
 * Last reviewed: April 2025
 *
 * IMPORTANT: Do not inline disclaimer text in components.
 * Always import from this file so updates propagate everywhere.
 */

export const DISCLAIMERS = {
  /**
   * Tier 1 — Global
   * Shown in footer, on first login, and in terms of use.
   */
  global: `FXD Inspector is a property inspection and reporting tool. All AI-generated content is a draft for professional review and must be verified by a qualified inspector or property manager before use. Nothing in this platform constitutes legal advice. Users are solely responsible for verifying all information before acting on it. FXD Inspector Limited accepts no liability for decisions made on the basis of content generated by this platform.`,

  /**
   * Tier 2 — AI Output (inline badge)
   * Short version shown on every AI-generated text block.
   * Disappears once the PM approves the section.
   */
  aiOutput: `AI-generated draft — review and verify before approving.`,

  /**
   * Tier 2 — AI Output (full version)
   * Shown in report footers and export PDFs.
   */
  aiOutputFull: `Sections marked as AI-generated were produced by the FXD Inspector AI engine from photos and inspector notes. They are drafts for professional review. The inspecting property manager is responsible for verifying the accuracy of all AI-generated content before approving and issuing any report. FXD Inspector Limited accepts no liability for the accuracy of AI-generated descriptions.`,

  /**
   * Tier 3 — Healthy Homes Assessment
   * Shown as a modal acknowledgement before starting any HH assessment.
   */
  healthyHomesAssessment: `This Healthy Homes assessment is an AI-assisted inspection tool designed to support property managers and landlords in identifying potential compliance issues. It is not a substitute for a professional assessment by a qualified Healthy Homes assessor or building professional.

Compliance determinations made by this tool are based solely on information provided by the inspector during the assessment and may not capture all relevant factors, exemptions, or site-specific conditions. Visual assessments from photographs have inherent limitations — not all compliance items can be determined from images alone.

The property manager and landlord are solely responsible for ensuring the property meets all requirements under the Healthy Homes Standards (Residential Tenancies Act 1986). FXD Inspector Limited accepts no liability for compliance decisions, penalties, or Tribunal outcomes arising from the use of this assessment tool.

If you are uncertain about any compliance matter, seek independent professional advice before issuing a Compliance Statement.`,

  /**
   * Tier 4 — Compliance Statement (pre-signature)
   * Full-screen, must be read before signature field appears.
   * This is the highest-risk disclaimer in the platform.
   */
  complianceStatement: `IMPORTANT — PLEASE READ CAREFULLY BEFORE SIGNING

By signing this Healthy Homes Compliance Statement, you are making a legal declaration under the Residential Tenancies Act 1986 (RTA) that the rental property described in this document currently meets the requirements of the Healthy Homes Standards.

You should be aware that:

1. A false or misleading compliance statement is a breach of the RTA and may result in financial penalties of up to $7,200 per standard.

2. This compliance statement has been prepared on the basis of the assessment conducted on the date shown. Compliance is an ongoing obligation — this statement does not guarantee compliance at any future date.

3. Physical items degrade over time. A property that was compliant at the time of assessment may fall out of compliance as heaters age, fans fail, insulation deteriorates, or windows are damaged. You are responsible for monitoring ongoing compliance.

4. This statement was prepared using the FXD Inspector AI-assisted assessment tool. You should not sign this statement unless you have independently reviewed the assessment findings and are personally satisfied that the property currently meets all applicable standards.

5. If you are unsure about any aspect of compliance, seek independent professional advice from a qualified Healthy Homes assessor before signing.

By proceeding to sign, you confirm that you have read and understood this notice and that you are authorised to sign this compliance statement on behalf of the landlord.`,

  /**
   * Tier 5 — Rental Appraisal
   */
  rentalAppraisal: `This rental appraisal is an AI-assisted estimate based on publicly available market data, comparable rental listings, and the property's assessed condition at the time of inspection. It is not a formal valuation and should not be relied upon as a substitute for a professional rental appraisal conducted by a licensed property manager or registered valuer. Actual market rents may vary significantly based on factors not captured in this assessment. This report is provided for discussion purposes only and does not constitute advice to increase, decrease, or maintain any rental rate.`,

  /**
   * Tier 5 — Improvement Recommendations
   */
  improvementRecommendations: `The improvement recommendations in this report are AI-generated suggestions based on visual assessment of the property. Cost estimates are indicative only and based on general market rates — actual costs will vary depending on materials, labour, location, and site conditions. Estimated rent uplift and capital value figures are projections based on comparable market data and are not guaranteed outcomes. All recommendations should be assessed by qualified tradespeople or professionals before proceeding. FXD Inspector Limited accepts no liability for decisions made on the basis of these recommendations.`,

  /**
   * Tier 5 — Maintenance Plan
   */
  maintenancePlan: `The maintenance plan and traffic light assessments in this report are AI-generated recommendations based on the property's inspection history and observed condition. They are not professional engineering or building assessments. Priority ratings and cost estimates are indicative only. All maintenance decisions should be assessed by qualified tradespeople before proceeding. FXD Inspector Limited accepts no liability for maintenance decisions made on the basis of this plan.`,

  /**
   * Tier 6 — Fixx Chat
   * Short, shown at top of every conversation.
   */
  fixxChat: `Fixx provides general information about NZ tenancy law and property management practice. This is not legal advice. For specific legal matters, consult a qualified legal professional or contact Tenancy Services at tenancy.govt.nz.`,

  /**
   * Tier 6 — Fixx Chat (full, shown in settings/about)
   */
  fixxChatFull: `Fixx is an AI assistant trained on publicly available New Zealand tenancy law and Healthy Homes Standards information. While Fixx strives to provide accurate and up-to-date information, legislation changes and individual circumstances vary. Nothing Fixx says constitutes legal advice. FXD Inspector Limited accepts no liability for actions taken on the basis of information provided by Fixx. For specific legal matters, consult a qualified legal professional or contact Tenancy Services (tenancy.govt.nz) or the Tenancy Tribunal.`,
} as const;

export type DisclaimerKey = keyof typeof DISCLAIMERS;
